import { Body, Controller, Get, Param, Post, Query } from '@nestjs/common';
import { ApiOkResponse, ApiOperation, ApiParam, ApiQuery, ApiTags } from '@nestjs/swagger';
import { BigNumber } from '@polymathnetwork/polymesh-sdk';

import { ApiArrayResponse } from '~/common/decorators/swagger';
import { ToBigNumber } from '~/common/decorators/transformation';
import { IsBigNumber } from '~/common/decorators/validation';
import { PaginatedParamsDto } from '~/common/dto/paginated-params.dto';
import { SignerDto } from '~/common/dto/signer.dto';
import { TransactionQueueDto } from '~/common/dto/transaction-queue.dto';
import { PaginatedResultsModel } from '~/common/models/paginated-results.model';
import { CreateInstructionDto } from '~/settlements/dto/create-instruction.dto';
import { InstructionIdDto } from '~/settlements/dto/instruction-id.dto';
import { InstructionAffirmationModel } from '~/settlements/model/instruction-affirmation.model';
import { InstructionModel } from '~/settlements/model/instruction.model';
import { SettlementsService } from '~/settlements/settlements.service';
import { createInstructionModel } from '~/settlements/settlements.util';

import { VenueDetailsModel } from './model/venue-details.model';

class IdParams {
  @IsBigNumber()
  @ToBigNumber()
  readonly id: BigNumber;
}

@ApiTags('settlements')
@Controller({})
export class SettlementsController {
  constructor(private readonly settlementsService: SettlementsService) {}

  @ApiTags('instructions')
  @ApiOperation({
    summary: 'Fetch Instruction details',
    description: 'The endpoint will provide the details of the Instruction',
  })
  @ApiParam({
    name: 'id',
    description: 'The ID of the instruction',
    type: 'string',
    example: '123',
  })
  @ApiOkResponse({
    description: 'Details of the Instruction',
    type: InstructionModel,
  })
  @Get('instructions/:id')
  public async getInstruction(@Param() { id }: IdParams): Promise<InstructionModel> {
    const instruction = await this.settlementsService.findInstruction(id);
    return createInstructionModel(instruction);
  }

  @ApiTags('venues', 'instructions')
  @ApiOperation({
    summary: 'Create a new Instruction',
  })
  @ApiParam({
    name: 'id',
    description: 'The ID of the Venue through which Settlement will be handled',
    type: 'string',
    example: '123',
  })
  @ApiOkResponse({
    description: 'The details of the Instruction being created',
    type: InstructionIdDto,
  })
  @Post('venues/:id/instructions')
  public async createInstruction(
    @Param() { id }: IdParams,
    @Body() createInstructionDto: CreateInstructionDto
  ): Promise<InstructionIdDto> {
    const { result: instructionId, transactions } = await this.settlementsService.createInstruction(
      id,
      createInstructionDto
    );

    return new InstructionIdDto({
      instructionId,
      transactions,
    });
  }

  @ApiTags('instructions')
  @ApiOperation({
    summary: 'Affirm an existing Instruction',
    description:
      'The endpoint will affirm a pending Instruction. All owners of involved portfolios must affirm for the instruction to be executed',
  })
  @ApiParam({
    name: 'id',
    description: 'The ID of the instruction to be affirmed',
    type: 'string',
    example: '123',
  })
  @ApiOkResponse({
    description: 'Details of the transaction',
    type: TransactionQueueDto,
  })
  @Post('instructions/:id/affirm')
  public async affirmInstruction(
    @Param() { id }: IdParams,
    @Body() signerDto: SignerDto
  ): Promise<TransactionQueueDto> {
    const { transactions } = await this.settlementsService.affirmInstruction(id, signerDto);

    return new TransactionQueueDto({ transactions });
  }

  @ApiTags('venues')
  @ApiOperation({
    summary: 'Fetch details of a Venue',
    description: 'This endpoint will provide the basic details of a Venue',
  })
  @ApiParam({
    name: 'id',
    description: 'The ID of the Venue whose details are to be fetched',
    type: 'string',
    example: '123',
  })
  @ApiOkResponse({
    description: 'Details of the Venue',
    type: VenueDetailsModel,
  })
  @Get('venues/:id')
  public async getVenueDetails(@Param() { id }: IdParams): Promise<VenueDetailsModel> {
    const venueDetails = await this.settlementsService.findVenueDetails(id);
    return new VenueDetailsModel(venueDetails);
  }

  @ApiTags('instructions')
  @ApiOperation({
    summary: 'List of affirmations',
    description:
      'The endpoint will provide the list of all affirmations generated by a Instruction',
  })
  @ApiParam({
    name: 'id',
    description: 'The ID of the instruction whose affirmations are to be fetched',
    type: 'string',
    example: '123',
  })
  @ApiQuery({
    name: 'size',
    description: 'The number of affirmations to be fetched',
    type: 'number',
    required: false,
  })
  @ApiQuery({
    name: 'start',
    description: 'Start index from which affirmations are to be fetched',
    type: 'string',
    required: false,
  })
  @ApiArrayResponse(InstructionAffirmationModel, {
    description:
      'List of all affirmations consisting of the target Identity and its current status',
    paginated: true,
  })
  @Get('instructions/:id/affirmations')
  public async getAffirmations(
    @Param() { id }: IdParams,
    @Query() { size, start }: PaginatedParamsDto
  ): Promise<PaginatedResultsModel<InstructionAffirmationModel>> {
    const { data, count, next } = await this.settlementsService.findAffirmations(
      id,
      size,
      start?.toString()
    );
    return new PaginatedResultsModel({
      results: data?.map(
        ({ identity, status }) =>
          new InstructionAffirmationModel({
            identity,
            status,
          })
      ),
      total: count,
      next,
    });
  }
}
